before_install:
  - gem install bundler
language: ruby
script: 'bundle exec rake ci'
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - jruby-18mode
  # - jruby-19mode Blacklisted for behaviour that does not occur under veritas-elasticsearch adapter http://travis-ci.org/#!/mbj/veritas-mongo-adapter/jobs/1779426
  - rbx-18mode
  - rbx-19mode
notifications:
  email:
    - mbj@seonic.net
